const mongoose = require('mongoose')

const AEFISchema= new mongoose.Schema({
   
    DReporting: Date,
    PHFName: String,
    PHFTName: String,
    Campaign: String,
    RImmunization: String,
    ReportingID: String,
    PRegion: String,
    TRegion: String,
    Zone: String,
    PWoreda: String,
    pTWoreda: String,
    Kebele: String,
    Age: String,
    Sex: String,
    Pregnant: String,
    Lactating: String,
    Phone: String,
    FacilityT: String,
    TFacilityT: String,
    HFName: String,
    HFTName: String,
    SpecifyF: String,
    HRegion: String,
    HTRegion: String,
    HSubCity: String,
    THSubCity: String,
    HWoreda: String,
    HFTworeda: String,
    Vaccine: String,
    NManufacture: String,
    Dose: String,
    BVaccine: String,
    DBatch: String,
    RAdministration: String,
    DExpiry: Date,
    COVaccine: String,
    PVaccination: String,
    DVaccination: Date,
    Donset: Date,
    DNotification: Date,
    VDReporting: Date,
    Serious: String,
    TextAReason: String,
    Outcome: String,
    Investigation: String,
    RRegion: String,
    RTRegion: String,
    RHSubCity: String,
    RTHSubCity: String,
    RHWoreda: String,
    RHFTworeda: String,
    RKebele: String,
    DNational: Date,
    NReporter: String,
    Profession: String,
    OfficerPhone: String,
    EPIWeek: String,
},
{ collection: "AEFI" }
)
mongoose.model("AEFI" , AEFISchema)
//module.exports = MeaselesMondel

