const mongoose = require('mongoose')

const FistulaSchema= new mongoose.Schema({
    ID:String,
    OnsetDate:String,
    Age:String,
    Residence:String,
    PRegion:String,
    TRegion:String,
    PSubCity:String,
    PWoreda:String,
    pTWoreda:String,
    Kebele:String,
   
    PMarital:String,
    Religion:String,
    TReligion:String,
    Educational:String,
    HFName:String,
    HFTName:String,
    FacilityT:String,
    TFacilityT:String,
    HWoreda:String,
    HFTworeda:String,
    HSubCity:String,
    THSubCity:String,
    HRegion:String,
    HTRegion:String,
    DReporting:String,
    Gravidity:String,
    TParity:String,
    NLivingC:String,
    BabyBorn:String,
    Mode:String,
    TypeF:String,
    Outcome:String,
    TimingOF:String,
    ANC:String,
    ANCK:String,
    WANC:String,
    TWANC:String,
    TANC:String,
    Cause:String,
    Delay1:String,
    Delay2:String,
    Delay3:String,
    Supplies:String,
    FCName:String,
    Phone:String,
    EPIWeek:String,
    pdf:String,
}, 
{ collection: "Fistula" }
)
mongoose.model("Fistula" , FistulaSchema)
//module.exports = MeaselesMondel

