const mongoose = require('mongoose')

const MalariaSchema= new mongoose.Schema({
    MMRN:String,
    MName:String,
    MAge:String,
    MSex:String,
    MPOccupation:String,
    TMPOccupation:String,
    MMarital:String,
    MFsize:String,
    MIncome:String,
    MPRegion:String,
    MTRegion:String,
    MPSubCity:String,
    MPWoreda:String,
    MpTWoreda:String,
    MResidency:String,
    MPhone:String,
    MFacilityT:String,
    MTFacilityT:String,
    HFName:String,
    HFTName:String,
    HRegion:String,
    HTRegion:String,
    HSubCity:String,
    THSubCity:String,
    HWoreda:String,
    HFTworeda:String,
    MDCollection:Date,
    latitude:String,
    longitude:String,
    MCfeatures:String,
    TMCfeatures:String,
    MOnsetDate:Date,
    MDHospital:Date,
    MAdmitted:String,
    MSampleT:String,
    MDSampleT:Date,
    MType:String,
    MResult:String,
    Mhistory:String,
    TMhistory:String,
    MProphylaxis:String,
    MPinfection:String,
    TMPinfection:String,
    MComorbidity:String,
    TMComorbidity:String,
    MComplications:String,
    TMComplications:String,
    Msuffering:String,
    MBednets:String,
    TMBednets:String,
    MRiskFactors:String,
    TMRiskFactors:String,
    MPregnant:String,
    MOutCome:String,
    MOutbreak:String,
    MFCName:String,
    EPIWeek:String,
    pdf:String,
}, 
{ collection: "Malaria" }
)
mongoose.model("Malaria" ,MalariaSchema)
//module.exports = MeaselesMondel
