const mongoose = require('mongoose')

const RabiesSchema= new mongoose.Schema({
   
    RpName:String,
    RPMRN:String,
    RPAge:String,
    RPSex:String,
    RPPhone:String,
    RPMarital:String,
    RPOccupation:String,
    TRPOccupation:String,
    RPRegion:String,
    TRRegion:String,
    RPSubCity:String,
    RPWoreda:String,
    RpTWoreda:String,
    RPKebele:String,
    RPZone:String,
    HRegion:String,
    RHTRegion:String,
    HSubCity:String,
    TRHSubCity:String,
    HWoreda:String,
    RHFTworeda:String,
    HFName:String,
    RHFTName:String,
    latitude:String,
    longitude:String,
    RExposureD:Date,
    RFacility:Date,
    RSite:String,
    RStatus:String,
    RwoundM:String,
    RwoundMD:Date,
    RPEPV:String,
    TRPEPV:Date,
    RNVaccination:String,
    TRNVaccination:String,
    RTypes:String,
    TRTypes:String,
    ROwner:String,
    RAnimals:String,
    RAfollowup:String,
    TRAfollowup:String,
    RTypeE:String,
    RReason:String,
    Rdevelop:String,
    TRdevelop:String,
    ROutcome:String,
    RFCName:String,
    RPhone:String,
    REPIWeek:String,
    pdf:String,
}, 
{ collection: "Rabies" }
)
mongoose.model("Rabies" , RabiesSchema)
//module.exports = MeaselesMondel
