const mongoose = require('mongoose')

const RelapsingFeverSchema= new mongoose.Schema({
    
    MRN:String,
    Test: String,
    PRegion:String,
    TRegion:String,
    PSubCity:String,
    PWoreda:String,
    pTWoreda:String,
    Kebele:String,
    HNumber:String,
    HRegion:String,
    HTRegion:String,
    HSubCity:String,
    THSubCity:String,
    HWoreda:String,
    HFTworeda:String,
    HFName:String,
    HFTName:String,
    PPatient:String,
    Sex:String,
    Age:String,
    POccupation:String,
    TPOccupation:String,
    Phone:String,
    OnsetDate:String,
    SeenHF:String,
    Admission:String,
    Discharge:String,
    LabBorrelia:String,
    Outcome:String,
    RFCase:String,
    Delousing:String,
    Insecticide:String,
    RiskFactors:String,
    TRiskFactors:String,
    Feature:String,
    TFeature:String,
    Transferred:String,
    TTransferred:String,
    TransferredIn:String,
    TTransferredIn:String,
    FCName:String,
    CPhone:String,
    EPIWeek:String,
},
{ collection: "RelapsingFever" }
)
mongoose.model("RelapsingFever" , RelapsingFeverSchema)
//module.exports = MeaselesMondel