const mongoose = require('mongoose')

const YellowFeverSchema= new mongoose.Schema({
    ID:String,
    YMRN:String,
    YPatient:String,
    YName:String,
    YPRegion:String,
    YTRegion:String,
    YPSubCity:String,
    YPWoreda:String,
    YpTWoreda:String,
    YHouse:String,
    YKebele:String,
    YAge:String,
    YSex:String,
    YPPhone:String,
    HFName:String,
    HFTName:String,
    YSpecifyF:String,
    HRegion:String,
    HTRegion:String,
    HSubCity:String,
    THSubCity:String,
    HWoreda:String,
    HFTworeda:String,
    YDReceived:String,
    YCondition:String,
    YDSeen:String,
    YDOnset:String,
    Ysymptoms:String,
    YSpecimen:String,
    YTSpecimen:String,
    YResult:String,
    YOutcome:String,
    YComments:String,
    YFCName:String,
    EPIWeek:String,
     pdf:String,
}, 
{ collection: "YellowFever" }
)
mongoose.model("YellowFever" , YellowFeverSchema)
//module.exports = MeaselesMondel